name: "test-job"
on:
  pull_request:
    branches:
        - main
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Insider CI action
        id: insiderci_action
        uses: ralvescosta/hackathon-team6-issue9-insiderci-action@v0.0.42
        with:
          email: ${{ secrets.insider_email }}
          password: ${{ secrets.insider_password }}
          applicationId: '1440'
          security: 10

