name: "test-job"
on:
  pull_request:
    branches:
        - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Insider CI action
        id: insiderci_action
        uses: ralvescosta/insiderci-action@v0.0.40
        with:
          email: ${{ secrets.insider_email }}
          password: ${{ secrets.insider_password }}
          technology: 'typescript'
          security: 10

