name: "test-job"
on:
  pull_request:
    branches:
        - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: ralvescosta/insiderci-action@v0.0.7
        with:
          email: 'email@email.com'
          password: 'password'
          technology: 'typescript'
          security: 50

